### ISSUE TITLE
k8s service example

### ISSUE THREAD

**Issue by echaouchna** [tetratelabs/istio-tools#15]
Hi,

is it possible please to add a full example including the k8s service

Thank you

**Comment by shaneqld** [comment]
a full example would be great - i too am trying to get this working through a gateway but getting 404s/405s. @echaouchna did you get this working?

**Comment by shaneqld** [comment]
Managed to get this working.  The [sample config](https://github.com/mukundha/istio-sample-grpc-transcoding) here helped a bit.

Things I needed to do in addition:
- create a named service port with name `http1` to allow http1 traffic through
- create additional match rules in the virtual service matching the http1 paths and delivering traffic to the http1 port of the service
- remove .spec.filters.listenerMatch.portNumber from the generated envoy filter -- for whatever reason, I can't get thing working regardless if I specify the container port or the http1/grpc service ports.

Hope this helps.

**Comment by nmnellis** [comment]
Im working on an example here that ill submit as a PR sometime, im still working on the protoc stuff but the generated files are already there. https://github.com/nmnellis/istio-tools/tree/example/grpc-transcoder#example

**Comment by shaneqld** [comment]
thanks @nmnellis, would be great if the example used the http1 path defined in the google.api.http option.

from my post above, i could not get this working with the `.spec.filters.listenerMatch.portNumber` option set in the envoy filter.  perhaps i'm doing something wrong, but if not, while it's not recommended as best practice to leave the portNumber option blank, would it be possible to omit portNumber if not specified?

**Comment by mkoppanen** [comment]
@shaneqld,

have you got a full working example? I keep hitting issues with http1 paths and I assume it has something to do with the portNumber issue

**Comment by shaneqld** [comment]
@mkoppanen this is what i'm using for what it's worth. this is for a service called `projects` which exposes the grpc service and rest service over https only. this is not a minimal example but thought it might be useful.  note that `.spec.filters.listenerMatch.portNumber` is removed from the envoyfilter.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: projects
spec:
...
        ports:
        - containerPort: 50051 # http2/grpc port of app
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: projects
spec:
  selector:
    app: projects
  ports:
  - name: grpc
    protocol: TCP
    port: 8080
    targetPort: 50051
  - name: http1
    protocol: TCP
    port: 8081
    targetPort: 50051
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: projects
spec:
  hosts:
  - projects.default.svc.cluster.local
  - projects.myapi.com
  gateways:
  - api
  - mesh
  http:
  # gRPC catch-all
  - match:
    - uri:
        prefix: /myapi.resourcemanager.v1.Projects/
    route:
    - destination:
        host: projects.default.svc.cluster.local
        port:
          number: 8080
  # Routes for json paths
  - match:
    - uri:
        regex: "^/v1/projects/?$"
    - uri:
        regex: "^/v1/projects/.*/?$"
    route:
    - destination:
        host: projects.default.svc.cluster.local
        port:
          number: 8081
    corsPolicy:
      allowOrigin:
      - "*"
      allowMethods:
      - OPTIONS
      - GET
      - POST
      - DELETE
      - PATCH
      allowCredentials: true
      allowHeaders:
      - Content-Type
      - Authorization
      maxAge: "1h"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: api
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 443 # for unsecure use 80
      name: grpc-http
      protocol: HTTPS # for insecure use HTTP
    hosts:
    - "*.myapi.com"
    # for insecure, remove tls section, otherwise make sure you set up your certs https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress-sds/
    tls:
      mode: SIMPLE
      minProtocolVersion: TLSV1_2
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      caCertificates: /etc/istio/ingressgateway-ca-certs/ca.crt
---
# GENERATED FILE
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: projects
spec:
  workloadLabels:
    app: projects
  filters:
  - listenerMatch:
      listenerType: SIDECAR_INBOUND
    insertPosition:
      index: BEFORE
      relativeTo: envoy.router
    filterName: envoy.grpc_json_transcoder
    filterType: HTTP
    filterConfig:
      services:
      - myapi.resourcemanager.v1.Projects
      protoDescriptorBin: Cqw......zM= # this part is much bigger
      printOptions:
        alwaysPrintPrimitiveFields: True
```

**Comment by mkoppanen** [comment]
@shaneqld,

after banging my head against the wall I eventually got the combination of portNumber and http1 paths to work. The key was to expose two ports in the service:

```
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: my-service
spec:
  ports:
    - name: grpc-8888 # notice that both are called grpc*
      port: 8888
      targetPort: 50051
      protocol: TCP 
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP  
  selector:
     app: my-service
```

And the following envoyfilter:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: my-service-transcoder
spec:
  workloadSelector:
    labels:
      app: my-service
  filters:
  - listenerMatch:            
      listenerType: SIDECAR_INBOUND
      portNumber: 8888
    insertPosition:
      index: BEFORE
      relativeTo: envoy.router
    filterName: envoy.grpc_json_transcoder
    filterType: HTTP
    filterConfig:
      print_options:
        add_whitespace: true
        always_print_enums_as_ints: false
        always_print_primitive_fields: true
        preserve_proto_field_names: false
      proto_descriptor: "/proto/proto.pb"
      services:         
        - myservice.Service
```
With this combination the service works as expected using curl.

**Comment by galen211** [comment]
I followed the k8 examples here on this thread and have the below configuration in Istio for my `EnvoyFilter`, `Deployment`, `Service`, & `VirutalService`.  I'm able to make successful gRPC calls and see http/1 traffic in the service, but when I invoke an `HTTP GET /v1/search/health` request (proto below), I get a 503 error with the message:
`Upstream remote reset in addition to 503 response code.
The request was denied by the external authorization service.`

Does anyone know how what might be done to diagnose and fix this issue? 

### Health.proto
```proto
syntax = "proto3";

package endpoints.company.v1.search;

import "google/api/annotations.proto";

service Health {
  rpc HealthCheck(HealthCheckRequest) returns (HealthCheckResponse) {
        option (google.api.http) = {
            get: "/v1/search/health"
        };
  };
}

message HealthCheckRequest {
}

/* A response to the HealthCheckRequest. Contains both a status code
 * and a status message */

message HealthCheckResponse {
  enum HealthStatus {
    OK = 0;
    UNKNOWN_HEALTH_STATUS = 1;
  }
  HealthStatus status_code = 1;
  string status = 2;
}
```

### Envoy Filter Configuration (Generated)
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: search
spec:
  workloadLabels:
    app: search
  filters:
  - listenerMatch:
      portNumber: 8080
      listenerType: SIDECAR_INBOUND
    insertPosition:
      index: BEFORE
      relativeTo: envoy.router
    filterName: envoy.grpc_json_transcoder
    filterType: HTTP
    filterConfig:
      services:
      - endpoints.company.v1.search.Health
      - endpoints.company.v1.search.Search
      - endpoints.company.v1.search.SystemInfo
      protoDescriptorBin: CqwF....
      printOptions:
        alwaysPrintPrimitiveFields: True
```

### VirtualService
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend
  namespace: testenv
spec:
  hosts:
  - "*"
  gateways:
  - frontend
  http:
  - match:
    - uri:
        prefix: /endpoints.company.v1.search
    route:
    - destination:
        port:
          number: 8090
        host: search
  - match:
    - uri:
        prefix: /v1/search
    route:
    - destination:
        port:
          number: 8080
        host: search
```

### Deployment & Service configuration:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: search
  labels:
    app: search
  namespace: testenv
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: search
  template:
    metadata:
      labels:
        k8s-app: search
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: search-service
        image: container/search-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50050
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  labels:
    app: search
  namespace: testenv
spec:
  ports:
  - name: grpc
    port: 8090
    targetPort: 50050
    protocol: TCP
  - name: http
    port: 8080
    targetPort: 50050
    protocol: TCP
  selector:
    app: search
```
